### ISSUE TITLE
Currency converter doesn't output "cur" parameter and incompatible with Prebid.js

### ISSUE THREAD

**Issue by dmitriyshashkin** [prebid/prebid-server#1141] opened 2019-12-11 16:50 UTC
Currency converter doesn't output "cur" parameter. Prebid.js doesn't know the bid's currency, assumes default one which results in double conversion.

E.g. 

1. adServerCurrency parameter for currency module of Prebid.js is set to EUR
2. Prebid.js sends a request to the prebid server, sets "cur" parameter to "EUR"
3. The server sends a request to appnexus bidder, the bidder bids in USD
4. Currency converter in prebid server converts bid to EUR, doesn't specify the currency
5. Prebid.js doesn't see the "cur" param in prebid server's response, assumes the bid to be in USD (it's hardcoded in DEFAULT_S2S_CURRENCY constant [here](https://github.com/prebid/Prebid.js/blob/master/modules/prebidServerBidAdapter/index.js#L20))
6. Prebid.js currency module sees bid in USD and converts it to EUR. Again.

**Comment by SyntaxNode** [comment] 2019-12-16 17:51
Looks like a duplicate of: https://github.com/prebid/prebid-server/issues/1140

**Closed by SyntaxNode** 2019-12-16 17:51 UTC
