### ISSUE TITLE
No more bids after upgrading from 0.134 to 0.185

### ISSUE THREAD

**Issue by derN3rd** [prebid/prebid-server#2116] opened 2021-12-20 19:43 UTC
Hey there,

I'm currently investigating why our prebid server is no more serving any bids since we upgraded to 0.185.0 (from 0.134.0).

Before the upgrade, ext.responsetimemillis would show, as well as the seatbid prop was included.
After the upgrade ext.responsetimemillis is missing, seatbid prop is missing as well and ext.warnings.general includes code 10002 "debug turned off for account" warning.

<details><summary>Sample Req</summary>
<p>

```json
{
	"id": "1eff9515-5894-48a7-9b25-d598b9934b1a",
	"test": 0,
	"source": {
		"tid": "1eff9515-5894-48a7-9b25-d598b9934b1a"
	},
	"imp": [{
		"id": "PrebidMobile",
		"secure": 1,
		"banner": {
			"format": [{
				"w": 300,
				"h": 250
			}]
		},
		"ext": {
			"prebid": {
				"storedrequest": {
					"id": "banner_mrec_android"
				}
			}
		}
	}],
	"device": {
		"make": "HUAWEI",
		"model": "ANE-LX1",
		"lmt": 0,
		"os": "android",
		"osv": "28",
		"language": "de",
		"w": 360,
		"h": 686,
		"pxratio": 3,
		"mccmnc": "262-3",
		"carrier": "freenet FUNK",
		"connectiontype": 1,
		"ifa": "82403366-8e80-47b1-b6f4-e1502e8b0c4c",
		"ua": "Mozilla/5.0 (Linux; Android 9; ANE-LX1 Build/HUAWEIANE-L21; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/76.0.3809.132 Mobile Safari/537.36"
	},
	"app": {
		"bundle": "de.appname.app.debug",
		"ver": "2.18.2",
		"name": "AppName Debug",
		"publisher": {
			"id": "appname-app"
		},
		"ext": {
			"prebid": {
				"source": "prebid-mobile",
				"version": "1.1.2"
			}
		}
	},
	"user": {
		"gender": "O"
	},
	"regs": {
		"ext": {}
	},
	"ext": {
		"prebid": {
			"cache": {
				"bids": {}
			},
			"storedrequest": {
				"id": "appname-app"
			},
			"targeting": {}
		}
	}
}
```

</p>
</details>

<details><summary>Sample Resp on 0.134.0</summary>
<p>

```json
{
	"id": "1eff9515-5894-48a7-9b25-d598b9934b1a",
	"seatbid": [
		{
			"bid": [
				{
					"id": "182606760123593613700",
					"impid": "PrebidMobile",
					"price": 0.151,
					"lurl": "https://tlx.3lift.com/s2s/loss?rid=${AUCTION_LOSS}&pr=${AUCTION_PRICE}&aid=182606760123593613700&ss=20",
					"adm": "<script>document.createElement('IMG').src=\"https://tlx.3lift.com/s2s/notify?px=1&pr=${AUCTION_PRICE}&ts=1640027654&aid=182606760123593613700&ec=2711_15052_11034914&n=GvsDaHR0cDovL3J0Yi5mci5ldS5jcml0ZW8uY29tL3RyaXBsZWxpZnRvcnRiYmFubmVyL2F1Y3Rpb24vbm90aWZ5P3Byb2ZpbGU9Mjc4JmltcD1rZmFyNmN2a21scTVTRHJYb01zSmE5VmxzSkR4dWhiWE40S2szcUtUZVVFOGJGYmlMS1VOQm13bnI3b004UFhERWRRZFJQSm0wQnNGa1o4cU1waTNMU0lSajZLZXRHVFdMRmZKQm1DNUdfNkwyRnhhMHFoNTd3aFNfVnFYYjVIa0gxZWNBQ0RUWTlkS1BUQ25USDZzdi1va2RMbGk0TE9TMlpjeHNQdm5Ebm5GY2RwUU5zZlJhQ1Q4eHBoNS10RV9SZHl0LUJoWHVBNEpGeU5vSmNvbzc4dFJpbGdkLTg4X0tDWEZVSGNELWYyUXV5T050N21rMWtjUkx1QWZuWGVzZTdMMWp5d3VkNW1paDlBZk8yQ2pESnJwblZjdXYzbmp2dEZGdHJPNEltQzFjdV96ZEsxbFljNXV4UjhxVW8xM2ZBZXRlV0NBX3o4MHg4MERRTFBzd0NvaEtUOTFHYk9qQkJXS3pVbkhCYjEwRkt5SGlFZm9hUEZCRXZ6QXVER0NrTEt4d1ItbkdXZVNuOUxnekViY0FLdEVDbFJlNGhjWEZMaTg0V2xRWWJN8gK5AQgAEhUxODI2MDY3NjAxMjM1OTM2MTM3MDAYACABKJcVMMx1QAFIAFABYApoAHDskh2QAQCYAQCoAQCwAbQBuAEFwAGXAcgBtAHgAQ%2FwAQD4AbQBgAKXAYgCD5ECAAAAAAAA8D%2BZAnsUrkfhesQ%2FoQIAAAAAAADwP6gCALACAMgCBNgCAPECZmZmZmZm5j%2F4ArIrgAOsAogD%2BgGQAwKYAwGgAwC4A5SHAsADAMgDANIDCDExMDM0OTE0%2BAIUiAMAkgMEMDEzYg%3D%3D\";document.createElement('IMG').src=\"https://eb2.3lift.com/pe?fid=10&peid=0&aid=182606760123593613700\";window.tl_auction_response_77679={\"settings\":{\"advertiser_name\":\"getir.com\",\"viewability\":{},\"type\":\"image\",\"additional_data\":{\"ss\":\"20\",\"bc\":\"AAABfdlECX0kVSLd1HdHWocNI7bbd88y1GSRSg==\",\"pr\":\"${AUCTION_PRICE}\",\"brid\":\"477548\",\"bmid\":\"2711\",\"biid\":\"5554\",\"aid\":\"182606760123593613700\",\"bcud\":\"180\",\"sid\":\"15052\",\"ts\":\"1640027654\"},\"billable_event\":1,\"billable_pixel\":\"https:\\/\\/tlx.3lift.com\\/s2s\\/notify?px=1&pr=${AUCTION_PRICE}&ts=1640027654&aid=182606760123593613700&ec=2711_15052_11034914&n=GvsDaHR0cDovL3J0Yi5mci5ldS5jcml0ZW8uY29tL3RyaXBsZWxpZnRvcnRiYmFubmVyL2F1Y3Rpb24vbm90aWZ5P3Byb2ZpbGU9Mjc4JmltcD1rZmFyNmN2a21scTVTRHJYb01zSmE5VmxzSkR4dWhiWE40S2szcUtUZVVFOGJGYmlMS1VOQm13bnI3b004UFhERWRRZFJQSm0wQnNGa1o4cU1waTNMU0lSajZLZXRHVFdMRmZKQm1DNUdfNkwyRnhhMHFoNTd3aFNfVnFYYjVIa0gxZWNBQ0RUWTlkS1BUQ25USDZzdi1va2RMbGk0TE9TMlpjeHNQdm5Ebm5GY2RwUU5zZlJhQ1Q4eHBoNS10RV9SZHl0LUJoWHVBNEpGeU5vSmNvbzc4dFJpbGdkLTg4X0tDWEZVSGNELWYyUXV5T050N21rMWtjUkx1QWZuWGVzZTdMMWp5d3VkNW1paDlBZk8yQ2pESnJwblZjdXYzbmp2dEZGdHJPNEltQzFjdV96ZEsxbFljNXV4UjhxVW8xM2ZBZXRlV0NBX3o4MHg4MERRTFBzd0NvaEtUOTFHYk9qQkJXS3pVbkhCYjEwRkt5SGlFZm9hUEZCRXZ6QXVER0NrTEt4d1ItbkdXZVNuOUxnekViY0FLdEVDbFJlNGhjWEZMaTg0V2xRWWJN8gK5AQgAEhUxODI2MDY3NjAxMjM1OTM2MTM3MDAYACABKJcVMMx1QAFIAFABYApoAHDskh2QAQCYAQCoAQCwAbQBuAEFwAGXAcgBtAHgAQ%2FwAQD4AbQBgAKXAYgCD5ECAAAAAAAA8D%2BZAnsUrkfhesQ%2FoQIAAAAAAADwP6gCALACAMgCBNgCAPECZmZmZmZm5j%2F4ArIrgAOsAogD%2BgGQAwKYAwGgAwC4A5SHAsADAMgDANIDCDExMDM0OTE0%2BAIUiAMAkgMEMDEzYg%3D%3D&b=1\",\"adchoices_url\":\"https:\\/\\/www.youronlinechoices.com\\/\",\"format_id\":10,\"render_options_bm\":0},\"assets\":[{\"asset_id\":0,\"banner_width\":300,\"banner_height\":250,\"banner_markup\":\"<script type='text\\/javascript' src='https:\\/\\/ads.eu.criteo.com\\/delivery\\/r\\/ajs.php?z=AAABfdlECX0kVSLd1HdHWocNI7bbd88y1GSRSg==&u=%7C%2FDSR%2Fy2kjeERfC%2BbNAEizNbJDGQAL8j33toWArjbP1Q%3D%7C&c1=glLBMxGOcDlLAi5oM4c9-3oF9oS9MYlb02bUzZUju1MxdrUP9kDhldjPe2amRM8Auut3_V6Nmp8u-wpF4OpHRCYcoKLXilcjxLeOzuczk2pQyDZ9eTjgHXdG03ByQdbye50h45pku6GzcEbxtyggBVHM0eF4R4GOyfg8mKLchje12_LQKf9PTQIHDMQlEwITaRQ7aEZJ4fcY0LQMudaxmFJFfsM0AoXYQYINgOebhlQY2EyCsB68s1CDLTLfzQ-BKujrp-IGAX-0opYK8WRxrCeYknIHvtf_YT7N5SANozX8i5wfK5SqG2cWs_OdV3vMJKbGkuXq0GPMTppBJ_3NpiHaveRAA-2388nhwLCW4Sn2ezBx-JQkRJqR1d0CAwv7ix6fjuqtI12Kw9I9bfUwvCPPZulN0K3msVPx9j2tU2nRRn1ScWybFrfhQksdGrgw_O5R8wiEmya9gf2jY5SQBwQLZ_aIy-LWmHefwgDrL8dRq5FpXgPfREwC3sXPWlzOuoVtQFlluFYCBt-MntdWa8-rUpKBMnfO&ct0={clickurl_enc}'><\\/script>\"}]};</script><script src=\"https://ib.3lift.com/ttj?inv_code=deAppname_app_general_300x250\" data-auction-response-id=\"77679\"></script>",
					"adomain": [
						"getir.com"
					],
					"crid": "2711_15052_11034914",
					"w": 300,
					"h": 250,
					"ext": {
						"prebid": {
							"cache": {
								"key": "",
								"url": "",
								"bids": {
									"url": "",
									"cacheId": "4dc9b8e4-9971-41e3-a28a-535932538cb5"
								}
							},
							"targeting": {
								"hb_bidder": "triplelift",
								"hb_bidder_triplelift": "triplelift",
								"hb_cache_id": "4dc9b8e4-9971-41e3-a28a-535932538cb5",
								"hb_cache_id_tripleli": "4dc9b8e4-9971-41e3-a28a-535932538cb5",
								"hb_env": "mobile-app",
								"hb_env_triplelift": "mobile-app",
								"hb_pb": "0.15",
								"hb_pb_triplelift": "0.15",
								"hb_size": "300x250",
								"hb_size_triplelift": "300x250"
							},
							"type": "banner"
						},
						"bidder": {
							"triplelift_pb": {
								"format": 10,
								"advertiser_name": "getir.com"
							},
							"prebid": {
								"meta": {
									"mediaType": "banner"
								}
							}
						}
					}
				}
			],
			"seat": "triplelift"
		}
	],
	"cur": "USD",
	"ext": {
		"responsetimemillis": {
			"openx": 9,
			"pubmatic": 10,
			"pubnative": 211,
			"rhythmone": 151,
			"smartadserver": 207,
			"triplelift": 192,
			"verizonmedia": 98,
			"visx": 30
		},
		"tmaxrequest": 400,
		"prebid": {
			"auctiontimestamp": 1640027654332
		}
	}
}
```

</p>
</details>
<details><summary>Sample Resp on 0.185.0</summary>
<p>

```json
{
	"id": "1eff9515-5894-48a7-9b25-d598b9934b1a",
	"nbr": 2,
	"ext": {
		"warnings": {
			"general": [
				{
					"code": 10002,
					"message": "debug turned off for account"
				}
			]
		},
		"tmaxrequest": 400,
		"prebid": {
			"auctiontimestamp": 1640027627054
		}
	}
}
```

</p>
</details>

As you can see we don't get any information anymore and also with test=1 I only get information from the files, but no external req data or bids.
Is there any obvious configuration mistake by us or any known issue with our type of setup?

Thanks in advance

## Our configurations

<details><summary>pbs.yaml</summary>
<p>

```yaml
cache.host: "<redacted>"
cache.scheme: "http"
cache.default_ttl_seconds.banner: 20
#cache.query: "env=prod&uuid=%PBS_CACHE_UUID%"
external_url: "<redacted>"
http_client:
  idle_connection_timeout_seconds: 65
in_memory_cache:
  ttl_seconds: 60 # 1 minute
  request_cache_size_bytes: 107374182 # 0.1GB
  imp_cache_size_bytes: 107374182 # 0.1GB
recaptcha_secret: "<redacted>"
stored_requests:
  filesystem: true
adapters:
  verizonmedia:
    disabled: false
    endpoint: https://s2shb.ssp.yahoo.com/admax/bid/partners/TEL
gdpr:
  default_value: "1"
  timeouts_ms:
    init_vendorlist_fetches: 5000
    active_vendorlist_fetch: 5000
debug:
  allow: true
  override_token: "<redacted>"

```

</p>
</details>

<details><summary>Our stored-request appname-app</summary>
<p>

```json
{
  "id": "appname-app",
  "imp": [
    {
      "id": "answer1"
    },
    {
      "id": "answer1_ios"
    },
    {
      "id": "banner_mrec_android"
    },
    {
      "id": "banner_mrec_ios"
    },
    {
      "id": "banner_mrec_android2"
    },
    {
      "id": "banner_mrec_android3"
    },
    {
      "id": "banner_mrec_test"
    },
    {
      "id": "general"
    },
    {
      "id": "general-ios"
    }
  ],
  "ext": {
    "prebid": {
      "aliases": {
        "appnexus-video": "appnexus",
        "districtm": "appnexus",
        "oftmedia": "appnexus",
        "web3": "smartrtb"
      },
      "bidadjustmentfactors": {
        "districtm": 0.85,
        "oftmedia": 0.94,
        "pubmatic": 0.78
      },
      "currency": {
        "adServerCurrency": "USD",
        "bidderCurrencyDefault": {
          "visx": "EUR"
        }
      },
      "targeting": {
        "pricegranularity": {
          "precision": 2,
          "ranges": [
            {
              "min": 0.03,
              "max": 2.0,
              "increment": 0.01
            },
            {
              "min": 2.02,
              "max": 3.8,
              "increment": 0.02
            },
            {
              "min": 3.9,
              "max": 20.0,
              "increment": 0.1
            }
          ]
        },
        "includewinners": true,
        "includebidderkeys": true
      }
    }
  },
  "tmax": 400
}
```

</p>
</details>

<details><summary>Our stored-imp banner_mrec_android</summary>
<p>

```json
{
  "id": "banner_mrec_android",
  "banner": { "format": [{ "w": 300, "h": 250 }] },
  "ext": {
    "openx": {
      <redacted>
    },
    "pubmatic": {
      <redacted>
    },
    "pubnative": {
      <redacted>
    },
    "rhythmone": {
      <redacted>
    },
    "triplelift": {
      <redacted>
    },
    "smartadserver": {
      <redacted>
    },
    "verizonmedia": {
      <redacted>
    },
    "visx": {
      <redacted>
    },
    "context": {
      "data": {
        "tagId": ["f7043b8f-8ed7-443e-bb89-<redacted>"]
      }
    }
  }
}

```

</p>
</details>

**Comment by Guilemon** [comment] 2021-12-22 07:58
it seems they have flipped the defaults for `gdpr.usersync_if_ambiguous`. refer https://github.com/prebid/prebid-server/issues/1783#issuecomment-810592476
if we use `gdpr.default_value: 1`, then auction won't happen until gdpr_consent is added to the request url
try with this setting:
```yaml
gdpr:
  default_value: "0"
```
Above should work irrespective of gdpr_consent sent
Had faced similar issue while upgrading previously

**Comment by derN3rd** [comment] 2021-12-22 10:22
Thanks!

That works. Are there any negative side effects of having it default to 0 instead of 1?

**Comment by Guilemon** [comment] 2021-12-22 13:38
Haven't seen any negative side effect from it so far.

**Comment by SyntaxNode** [comment] 2022-01-04 22:42
> After the upgrade ext.responsetimemillis is missing, seatbid prop is missing as well 

@Guilemon correctly identified this is caused by GDPR settings. We introduced a change in [0.164.0](https://github.com/prebid/prebid-server/releases/tag/v0.164.0) which removes the `gdpr.usersync_if_ambiguous` setting in favor of a new `gdpr.default_value` setting that, in our opinion, is less confusing. This is a mandatory setting without a default, so the host company must provide it otherwise PBS will fail to start. This is in response to several GitHub issues opened on the topic.

The `gdpr.default_value` setting is used for `regs.ext.gdpr` if it's not present in the request. So, if a request does not specify `regs.ext.gdpr` and the `gdpr.default_value` is `1`, then `regs.ext.gdpr` will be treated as if it's set to `1` and the lack of a consent string will be interpreted as lacking permission to run an auction (TCF2 Purpose 2).

Please consult with your company's legal department for how to configure Prebid Server GDPR settings.

> as well and ext.warnings.general includes code 10002 "debug turned off for account" warning.

I see you've set `debug.allow` in your settings file, but this is not a valid setting for Prebid Server. The setting you're interested in is `account_defaults.debug_allow` which defaults to `true`. Is this your complete configuration file? Are you perhaps also using environment variables or have an account configuration source configured?

**Closed** 2022-01-06 15:43 UTC
