### ISSUE TITLE
GET Vendor list, json malformed so cookie_sync not working

### ISSUE THREAD

**Issue by mouchii** [prebid/prebid-server#1722] opened 2021-02-24 10:28 UTC
Hello,

I have a problem, when i start my pbs server, i got this error message : 

`GET https://vendor-list.consensu.org/v2/archives/vendor-list-v1.json returned malformed JSON. Cookie syncs may be affected. Error was data.vendors was undefined or had no elements. Body was {"gvlSpecificationVersion":2,"vendorListVersion":1,"tcfPolicyVersion":2,"lastUpdated":"2019-09-12T16:05:11Z","...................`

This is why i think that my cookie_sync endpoint return always an empty array "bidder_status" except when i set gdpr to false in config.

Someone already have this problem ?

Thanks

**Comment by bretg** [comment] 2021-02-24 14:55
The malformed TCF1 list shouldn't be related to the /cookie_sync endpoint because you should be using TCFv2. I'll assume that you're specifying bidders and GDPR params in the /cookie_sync POST body as described in https://docs.prebid.org/prebid-server/endpoints/pbs-endpoint-cookieSync.html . 

The detailed GDPR documentation as at https://docs.google.com/document/d/1g0zAYc_EfqyilKD8N2qQ47uz0hdahY-t8vfb-vxZL5w/edit#

Make sure you're passing a **TCFv2** GDPR consent string in /cookie_sync with Purpose 1 permissions for the biddercodes listed in the `bidders` argument.

If it still doesn't work, please post your test /cookie_sync POST body including the GDPR params

**Comment by SyntaxNode** [comment] 2021-02-24 18:55
> Someone already have this problem ?

Yup. It's also mentioned in https://github.com/prebid/prebid-server/issues/1689. The root cause is our GDPR library incorrectly assumes the GVL should have at least one vendor defined. We thought it this was safe, but version 1 of the TCFv2 GVL surprised us with no vendor definitions.

PBS-Go 0.148.0 will no longer preload this version to avoid the warning. We'll soon update the library to remove that error check.

**Comment by SyntaxNode** [comment] 2021-03-08 01:08
I'm closing this issue. Please follow https://github.com/prebid/prebid-server/issues/1689 for update.

**Closed by SyntaxNode** 2021-03-08 01:08 UTC
