### ISSUE TITLE
large amount of empty Video UUID caches for Appnexus

### ISSUE THREAD

**Issue by spormeon** [prebid/prebid-server#1562] opened 2020-11-02 20:24 UTC
I'm using s2s for some video ads and i'm seeing a large amount of empty cache urls in effect, this seems to be for appnexus bidder when using the appnexus s2s

example: https://prebid.adnxs.com/pbc/v1/cache?uuid=fc21c988-2455-41cf-beb7-40e9f9285d24   its empty even if i paste one of these urls just in a browser tab, well within the TTL of 60

It seems random, as in some will work, some are not, but they are all within the TTL of 60

here is a Quadruplex capture, where its empty and giving a error 303 because its empty but its been called well within the TTl 60:
![DevTools_-_cheftalk_com_forums_professional-pastry-chefs_26__and_AWS_CloudFront_Management_Console](https://user-images.githubusercontent.com/8503167/97915285-25dd2480-1d49-11eb-89fd-27d6855dbbe7.png)

This is also following through into appnexus UI stats as i see "impressions" eg. 325 imps  but only 2 resold, so 323 have disapeared into thin air

**Comment by spormeon** [comment] 2020-11-04 10:52
one thing that is different now as well is appnexus is sending a different hb_cache_host:   prebid.ams1.adnxs.com  where as before  it was sending    hb_cache_host:    prebid.adnxs.com   .prebid.adnxs.com is used in the dfp creative redirect as well, not the one they are now sending , would this have an effect,  both seem to show if put in a browser with the same uuid

**Comment by SyntaxNode** [comment] 2020-11-05 17:22
AppNexus/Xandr will only cache the response in a single data center. If their global load balancer doesn't send you to the same data center as the client's auction, the result will not be found.

Is `prebid.adnxs.com` hardcoded somewhere or is Prebid Server incorrectly sending back a `prebid.adnxs.com` url in the response?

**Comment by spormeon** [comment] 2020-11-05 17:25
this is with the appnexus hosted prebid server, so prebid.adnxs.com is hardcoded in the dfp creative with this: https://prebid.adnxs.com/pbc/v1/cache?uuid=%%PATTERN:hb_uuid%%

**Comment by spormeon** [comment] 2020-11-06 11:15
another thing i've also noticed is the TTL, when on S2S the TTL goes to about 60 for all bidders, where as client side its on various TTL's ranging 100-3600 depending on bidder.   I don't see why this should be different S2S side?  It seems the bidder is determining it client side, where as the server is determining it S2S side? but why such huge difference.  e.g appnexus S2S = 60 TTL, client side 3600 TTL, if its exactly the same ad coming through on both, you have 60 secs V's 60 mins  with exactly the same cache path apart from the UUID

**Comment by spormeon** [comment] 2020-11-11 10:10
any word or ideas,  I've had to ditch s2s basically due to these stats issues, client side basically gets 99% accurancy on pinged back stats, s2s at best 40%

**Comment by SyntaxNode** [comment] 2020-11-13 06:12
> so prebid.adnxs.com is hardcoded in the dfp creative

I'm not personally familiar with DFP creatives. Could you please point me to where that pattern of `https://prebid.adnxs.com/pbc/v1/cache?uuid=%%PATTERN:hb_uuid%%` is hardcoded? Seems like it should be updated to include the `hb_cache_host` key.

> appnexus and districtm are sending back: https://prebid.ams1.adnxs.com , which is pushed to dfp with key-value, all the other bidders im using with prebid server are sending back https://prebid.adnxs.com and they work fine, from what i see.

DistrctM is an alias of AppNexus, so at least it makes sense that both behave the same. The AppNexus adapter shouldn't be receiving any special treatment in terms of the cache url returned. I'd be happy to look into that. Could you please share an example request where other bidders are sending back `https://prebid.adnxs.com`?

> another thing i've also noticed is the TTL, when on S2S the TTL goes to about 60 for all bidders, where as client side its on various TTL's ranging 100-3600 depending on bidder.

The default TTL on AppNexus hosted servers is 3600 for video ads, but it can be overridden by the either the bid request or the bid response. If you could please share an example request, I can check if one of those is the case here.

**Comment by spormeon** [comment] 2020-11-13 15:29
its here:   https://docs.prebid.org/adops/setting-up-prebid-video-in-dfp.html

i'll try get a bid responce with the TTL 60 showing

**Comment by SyntaxNode** [comment] 2020-11-13 18:55
@spormeon Thank you. We also discussed this issue at today's Prebid Server Committee meeting.

First, I'd like to be clear that nothing has changed with the `https://prebid.adnxs.com` domain. It has always routed users to their closest Xandr data center and cached results have never been synced between data centers. We enhanced Prebid Server this year to send back a data center specific cache url to avoid edge cases where users are not reliably routed to the same data center, but the `https://prebid.adnxs.com` domain still works too. It would seem you have encountered a need for the more precise urls though, as is common for instream video.

I'm told by @bretg that DFP will not allow a parameterized url, so we need to explore other options. We're currently considering either having Prebid Cache return a redirect if the item is cached on a different server or to have Prebid Cache act as a proxy and use faster internal connections to essentially do the same thing.

We'll begin planning the feature next week and will prioritize its development. I don't have a workaround suggestion until then.

> i'll try get a bid responce with the TTL 60 showing

Yes, please. Let's see if we can help out there too.

**Comment by spormeon** [comment] 2020-11-13 19:54
@SyntaxNode have you got a way i can contcat you direct,  I have a test page with the S2S setup but dont want to put in an open forum

**Comment by SyntaxNode** [comment] 2020-11-13 19:59
@spormeon Yes. Please send an email to prebid-server@xandr.com. Would be nice for GitHub to allow private messaging for situations like this.

**Comment by spormeon** [comment] 2020-11-16 14:56
update:  the stats issue i sorted out, darn debug: true,  sends a "test" s2s call, why its tied to debug i dont have a clue, maybe one to split out?  and the TTL, i think i worked that one out, seems ca be set  with   defaultTtl: 300, 400, 500 etc etc

**Comment by bretg** [comment] 2020-11-16 17:35
@spormeon - I think you're bringing up an issue we'd let fall through cracks, but just to be sure...

Right now adding `pbjs_debug=true` to the query string will cause the pbsBidAdapter to add `test:1` to the OpenRTB. We're now at a point where it's reasonable to change this behavior to add `ext.prebid.debug:1` instead.

I'll bring this up in the next PBJS meeting -- would like to discuss whether we want to add a pbjs_test=true as well.

**Comment by spormeon** [comment] 2020-11-16 17:51
I had it on here, obviously while testing and trying to debug this thing and left on in a 'semi Live" test 

![prebidVideo_js_—_Prebid_Publishers__Workspace_](https://user-images.githubusercontent.com/8503167/99288941-38b92400-2834-11eb-89f8-fcf0d33d532c.png)

**Comment by rmertens** [comment] 2020-12-03 15:15
any news on the datacenter part of this issue?

**Comment by SyntaxNode** [comment] 2020-12-03 18:49
@rmertens Yes. The server aspect of this issue was discussed by the Prebid Server Committee. We are exploring ways for Prebid Cache to identify a request intended for a different instance and forward it on. We'll be posting a proposal for that soon.

The root cause of the original issue was unrelated to the server affinity mentioned above. It turned out to be related to the cache ttl.

This does bring up a "blind spot" in the cache infrastructure though which we'll be addressing. As fas I can tell by our metrics, this doesn't appear to be a widespread problem.

**Comment by bretg** [comment] 2020-12-03 20:55
Is there evidence of widespread issues here @rmertens ? The issue from the original poster was more about cache time-to-live and not datacenter if I understand it correctly. I'm with Magnite and we have the same cache structure -- if you hit prebid-server.rubiconproject.com, the global load balancing system will direct you to one of 6 datacenters. Your video or AMP ads will be cached only in that datacenter. A few milliseconds later when you're ready to retrieve that cached item, your browser will hit the same domain which will almost always take you back to the same datacenter. The only time it wouldn't work is if the datacenter went down or if your local host decided to refresh its DNS cache right at that moment.

Both Appnexus and RubiconProject have been running with this architecture for years and it has not been surfaced as a problem. It would show up as a terrible render rate for video or AMP, and our managed service doesn't exhibit that issue.

So if anyone has evidence, would like to hear about it. It would be impossible (or at least prohibitively expensive) to try to replicate caches of this size globally within milliseconds. The team will look into some kind of feature (e.g. a "cache relay") that can help with the odd request that falls through the cracks, but that will affect ad latency.

**Comment by spormeon** [comment] 2020-12-03 21:42
I've actually seen "blank" cache urls since setting the TTL myself in effect.  It can actually be way more than a few ms's before you "go collect" the cache, especially if your using a VMAP?, could be a couple of minutes? Thats much enough time to have been sent to a different datacentre?  In this VMAP or maybe midroll, post roll scenario, would you even have fired anything, as doesn't that only fire once the cache url has been "collected" and the vast or whatever in it has fired?

**Comment by rmertens** [comment] 2020-12-04 09:43
I don't have evidence of widespread issues indeed but just as @spormeon,  we've seen cases where we check the cache (manually) well within 60 secs after storing something there, and the cache has no value for the key. I don't know for sure if that's related.

**Comment by spormeon** [comment] 2020-12-05 09:02
i've done a little test here for yesterday,  its not fool proof but i think it might be in the right direction.  For appnexus alone,  i did 881 imps recorded in dfp for prebid s2s,  appnexus records 666 imps,  with a video start rate of 99.5% and a video error rate of 23 imps.  Thats a 25% loss of impressions, with a wild presumption that those are due to the uuid problem

**Comment by SyntaxNode** [comment] 2021-08-20 07:27
Closing this issue since we have the separate proposal in https://github.com/prebid/prebid-server/issues/1620.

The overall error rate of Prebid Cache retrievals with the Xandr/AppNexus servers is less than 1%. Higher rates are likely attributed to a biased effect of the geo issue described in this thread or specifying a ttl which is too short.

**Closed by SyntaxNode** 2021-08-20 07:27 UTC
Labels: feature request
