### ISSUE TITLE
Reuse single adapter on multiple platforms

### ISSUE THREAD

**Issue by Aigolkin1991** [prebid/prebid-server#1371] opened 2020-06-26 06:07 UTC
Is there a way which allows reuse single adapter for two identical platforms. For example we have platform `a` with endpoint http://a.com/rtb and and platform `b` with endpoint http://b.com/rtb - both are identical, only difference - endpoint address, can adapter be configured by publishers, to connect to preferred platform

**Comment by SyntaxNode** [comment] 2020-06-29 17:50
@hhhjort Can this be accomplished with aliases?

**Comment by SmartyAdman** [comment] 2020-06-29 17:56
How this works in terms of prebid server?

> @hhhjort Can this be accomplished with aliases?

How does aliasses works in terms of prebid server

**Comment by hhhjort** [comment] 2020-06-29 19:29
See https://github.com/prebid/prebid-server/blob/master/docs/endpoints/openrtb2/auction.md and search for Bidder Aliases. Basically you declare an alias which PBS treats as a separate bidder, but uses the same bidder code as the core bidder. This configuration is done in the request, but the PBS host can also configure a default request that gets merged in with every incoming request to "hard code" an alias into a PBS instance so the alias does not need to be declared in every request. But that only solves half of the problem, if you have one request that needs to go to both a.com and b.com.

The other part of the problem is supporting additional endpoints. Each bidder defines its own set of bidder parameters so that the bidder can properly process the bid request. You will have to include enough information in your bidder parameters for the adapter to figure out the correct endpoint to hit. You do not do this by simply having the hostname be a parameter without strict domain name checking. Having an adapter that can hit arbitrary domain names is just asking for PBS to be used to conduct a DDOS on websites. If the set of domains is continuously evolving, I might suggest a map of "common name" to host name be used ... each adapter can be given an arbitrary JSON blob of additional config parameters in the PBS config where the PBS host can update a map with new entries as they come online. Or if you can develop some simple logic that can verify a given domain name is one of yours that is ideal. Adapters when they fire off requests can make requests to any URL, they are not restricted to the "default" endpoint specified in the configuration.

**Comment by bretg** [comment] 2020-07-04 14:21
Which scenario are we considering:

1) a single adunit going to multiple auction endpoints (a.com and b.com)
2) adunits referring to 'bidderA' go to a.com using the bidderA adapter, and adunits referring to 'bidderB' go to b.com, but also using the bidderA adapter.

I am against the request OpenRTB specifying a destination URL, but I'm not against allowing each alias to have a separate endpoint. If that's the case, they probably have different cookie-sync endpoints as well, right?

**Comment by Aigolkin1991** [comment] 2020-07-08 11:24
The case is like in 2, we are developing single platform , and each client owns individual copy of platform on its individual domain, and some of them willing to have prebedi-server support. The number of such clients could be huge enough so separate adapter for each of them is a bad way and aliases looks good to solve this problem

**Closed** 2020-07-08 11:24 UTC
