### ISSUE TITLE
Bidder-defined TTL

### ISSUE THREAD

**Issue by Aigolkin1991** [prebid/prebid-server#1386] opened 2020-07-08 11:42 UTC
I'm looking for way to set TTL inside our adapter for bid.adm (banner,video,native separate) - this is important for our demand source, which have TTL for win and imp events. Currently we are getting discrepancy between supply source and demand in number of impressions, this occurs when adm is being rendered after impression record on our demand side has been already timed out, in this case only supply partner counts impression

**Comment by bretg** [comment] 2020-07-16 13:30
Here's a cut at a technical description:

1) bidders can set seatbid.bid.exp in seconds
2) this value is passed back to clients who should respect it
3) if present, this value is used as the cache TTL for Prebid Cache instead of the account-level TTL or the default TTL
   3a) covers scenarios of both bid-cache (AMP and Mobile) and VAST XML (Video)

Will that cover it?

**Comment by patmmccann** [comment] 2020-07-16 19:19
appears to be a duplicate of https://github.com/prebid/prebid-server/issues/237

**Comment by Aigolkin1991** [comment] 2020-07-18 11:24
> appears to be a duplicate of #237

Nope, proposition which you are talking about is about setting TTL from supply side (Prebid.js), my question is about setting TTL from demand side. @bretg  gave the answer which i was looking for

**Comment by bretg** [comment] 2020-07-18 13:46
Wait, this feature isn't implemented yet - my description was a more detailed feature proposal.

**Comment by SyntaxNode** [comment] 2020-07-24 15:40
Discussed by Prebid Server Committee.

Support was added in PrebidJS in https://github.com/prebid/Prebid.js/pull/5419 to look in the `seatbid.bid.ttl` field. Unless we're misunderstanding the PBJS object model, that field is not defined in OpenRTB 2.5. PBS is using third party libraries for the OpenRTB spec and can only extend the spec via the defined ext fields. With this clarification, `vseatbid.bid.exp` is fine.. but support needs to be added to PrebidJS.

**Comment by bretg** [comment] 2020-08-04 19:48
I believe you're saying is that prebid/Prebid.js#5419 was incorrect --  `seatbid.bid.ttl` will never be set by PBS.

So in addition to the steps described in my comment above, we ought to go back and change PBJS to look for exp instead of ttl.

**Comment by bretg** [comment] 2020-08-04 21:06
@rpanchyk has pointed out that PBS-Java already looks for seatbid.bid.exp. 

PBS-Go does too, but adds a 60-second buffer and uses the lower of the request.imp.exp and response.seatbid.bid.exp

exchange/auction.go
TTLSeconds: cacheTTL(expByImp[impID], topBidPerBidder.bid.Exp, defTTL(topBidPerBidder.bidType, defaultTTLs), ttlBuffer),

```
func cacheTTL(impTTL int64, bidTTL int64, defTTL int64, buffer int64) (ttl int64) {
	if impTTL <= 0 && bidTTL <= 0 {
		// Only use default if there is no imp nor bid TTL provided. We don't want the default
		// to cut short a requested longer TTL.
		return addBuffer(defTTL, buffer)
	}
	if impTTL <= 0 {
		// Use <= to handle the case of someone sending a negative ttl. We treat it as zero
		return addBuffer(bidTTL, buffer)
	}
	if bidTTL <= 0 {
		return addBuffer(impTTL, buffer)
	}
	if impTTL < bidTTL {
		return addBuffer(impTTL, buffer)
	}
	return addBuffer(bidTTL, buffer)
}
```

So I'd suggest two things here:

1) PBS-Java could align better with PBS-Go
2) PBJS needs to change

other than that, we're good here?  Bid adapters can already set bidresponse.exp and it will be respected.

**Comment by SyntaxNode** [comment] 2020-09-12 05:20
@bretg Did the change to Prebid.js resolve this thread?

**Comment by bretg** [comment] 2020-09-25 15:47
@Aigolkin1991 - we believe this is adequately resolved now, except perhaps in bid adapter developer documentation. Just set the `exp` attribute on the bidResponse.

**Closed by bretg** 2020-09-25 15:47 UTC
Labels: enhancement
