### ISSUE TITLE
Pubmatic responding with unexpected banner sizes

### ISSUE THREAD

**Issue by bjorn-lw** [prebid/prebid-server#1823] opened 2021-04-26 07:58 UTC
When testing version 0.155, I noticed that Pubmatic started to respond with banner sizes not present in the bid request, whereas it worked just as it should in the previously installed version (0.139.1).

After some testing, I noticed this behavior started to happen with version 0.153 and my uninitiated guess is that it may have something to do with https://github.com/prebid/prebid-server/pull/1759.

I added two comments in the PR a little more than a week ago, but no one picked it up so I thought I'd try creating an issue here instead, but please refer to my comments there as well.

I realize this is quite vague and I'm having trouble setting up a proper test case: I can see the problem in our statistics, but it's hard to repeat when actually trying. It was about a percentage of all responses that had the issue last time I checked, but it's one percent too much as it was working perfectly the version before that. :)

Please let me know whatever I can do to help solve this: I'm not a good enough GO programmer to actually being able to figure out the issue in code and I'm hesitant to give away our customer's SSP id's in this PR, but maybe that can be done outside this context with the person investigating the issue?

**Comment by SyntaxNode** [comment] 2021-04-26 14:11
Thank you for opening an issue. We sometimes miss comments made on closed PRs. The circumstantial evidence seems strong. I'll take a look where we might've introduced an error with that PR.

**Comment by SyntaxNode** [comment] 2021-04-26 16:25
@bjorn-lw Found the bug. You're correct that it was caused by PR https://github.com/prebid/prebid-server/pull/1759. In the case of no ad slot id, the height was copied to both width and height. There was no test coverage for this error. I've opened a PR to fix the error, added a test case, and I included some miscellaneous code refactor while I was in there.

I'm going to close this issue with the error has been identified and PR opened. Please review the PR and we'll include it in this week's release.

**Closed by SyntaxNode** 2021-04-26 16:25 UTC
Labels: PBS-Go, bug
