### ISSUE TITLE
AppNexus documentation issue: placement_id not mentioned in bidder params documentation

### ISSUE THREAD

**Issue by bjorn-lw** [prebid/prebid-server#2103] opened 2021-12-06 10:28 UTC
According to https://github.com/prebid/prebid-server/blob/master/static/bidder-params/appnexus.json placementId is deprecated and placement_id should be used instead but the documentation (https://github.com/prebid/prebid.github.io/blob/master/dev-docs/bidders/appnexus.md) on prebid.org doesn't mention that the prebid server parameter differs. Prebid Server is specifically mentioned in the description of the parameter but nothing about that it has a different name in PBS.

https://github.com/prebid/prebid-server/blob/da310321e3248fb1078f0e8bb85503355b7b1fee/static/bidder-params/appnexus.json#L8-L15

What is the reason the placement id parameter names differs and can we change that or document it properly?

**Comment by MartianTribe** [comment] 2021-12-09 14:25
@bjorn-lw  Thanks for bringing this up. I'm checking with the Xandr devs to have them review and then I'll get it updated.

**Comment by VeronikaSolovei9** [comment] 2021-12-14 21:11
PR with updates: https://github.com/prebid/prebid.github.io/pull/3464

**Comment by bjorn-lw** [comment] 2022-01-13 19:06
@bretg @VeronikaSolovei9 Thanks, it seems to solve the issue so it's clear what parameter name should be used for PBS and PBJS respectively.

What I don't understand though is why the parameter name should differ between PBS and PBJS. Why can't both be "placementId" or "placement_id"?

**Comment by VeronikaSolovei9** [comment] 2022-01-24 08:14
Please refer to this issue: https://github.com/prebid/prebid-server/pull/412

**Comment by VeronikaSolovei9** [comment] 2022-01-24 08:17
Prebid Server supports both `placementId` and `placement_id` (case sensitive). We encourage to use `placement_id`.

**Comment by bjorn-lw** [comment] 2022-01-24 08:20
> Prebid Server supports both `placementId` and `placement_id` (case sensitive). We encourage to use `placement_id`.

Great. So why does Prebid client only support CamelCase?

"placement_id (PBS) or placementID (PBJS)"

**Comment by bretg** [comment] 2022-05-26 20:03
@VeronikaSolovei9 and @SyntaxNode - I agree with @bjorn-lw here. It's bad for client/server A/B testing to have different parameters. See https://docs.prebid.org/dev-docs/modules/s2sTesting.html -- this module can't be used for bidders who have different params client-vs-server.

Please settle on a standard nomenclature that's supported by both client and server.

**Comment by bretg** [comment] 2022-12-19 19:55
Closing this issue as duplicate of https://github.com/prebid/prebid-server/issues/2106

**Closed by bretg** 2022-12-19 19:55 UTC
