### ISSUE TITLE
Add support for alias in prebid-server

### ISSUE THREAD

**Issue by jdelhommeau** [prebid/prebid-server#271] opened 2018-01-04 10:53 UTC
Some clients uses alias in order to call multiple seat from AppNexusAst adapter (each seat belonging to a different monetization partner from the publisher).
Alias works fine for client side implementation.
However, alias aren't compatible with server side implementation at the moment.

Having support for server side for alias would allow to optimize performances for those AppNexus partners, as one single call would be made instead of current multiple calls. Also using AppNexus hosted prebid server solution would allow not to impact cookie sync, so only benefit for people having multiple AppNexus partners.

**Comment by dbemiller** [comment] 2018-01-04 13:51
Yes... this actually duplicates #11, and will be coming soon.

Just to be clear, which types of prebid.js aliases are important to you? Some are static in the code (defined by adapters themselves), and others can be defined by the publisher page through `$$PREBID_GLOBAL$$.aliasBidder`.

**Comment by dbemiller** [comment] 2018-01-18 16:10
We chatted offline... the ask here is specifically for _dynamic_ aliases, which makes it a duplicate of [this comment](https://github.com/prebid/prebid-server/issues/11#issuecomment-344307269).

Will close this to consolidate the tickets.

**Closed by dbemiller** 2018-01-18 16:10 UTC
