### ISSUE TITLE
Currency file is missing EUR

### ISSUE THREAD

**Issue by bjorn-lw** [prebid/prebid-server#1791] opened 2021-04-06 12:33 UTC
Since Tuesday Apr 6 CET ~13.55, the Prebid currency conversion rates endpoint is no longer returning EUR as a currency which is quite a head ache.

https://cdn.jsdelivr.net/gh/prebid/currency-file@1/latest.json?date=20210406

When it started, it didn't happen every time but now it seems to be happening with every reload.

Not sure how to escalate this and how the file is generated so I try here first.

**Comment by bjorn-lw** [comment] 2021-04-06 12:34
It may have resolved itself while I was writing this, but I let the issue stand. I'd like to know how to escalate issues like this and how the file is generated?

**Comment by patmmccann** [comment] 2021-04-06 13:10
Possible duplicate of https://github.com/prebid/Prebid.js/issues/6524

**Comment by bretg** [comment] 2021-04-08 21:41
Closing with reference to https://github.com/prebid/Prebid.js/issues/6524

**Closed by bretg** 2021-04-08 21:41 UTC
